"use client";

import { useEffect, useState } from "react";
import { adminApi } from "@/lib/api/admin";
import { ApiError } from "@/lib/api/client";
import type { UserProfile } from "@/lib/api/users";

export function AdminUsersView() {
  const [users, setUsers] = useState<UserProfile[]>([]); const [filter, setFilter] = useState<"" | UserProfile["status"]>(""); const [error, setError] = useState(""); const [acting, setActing] = useState("");
  useEffect(() => { adminApi.users(filter || undefined).then((page) => setUsers(page.content)).catch((caught) => setError(caught instanceof ApiError ? caught.message : "Users could not be loaded.")); }, [filter]);
  async function change(user: UserProfile) { setActing(user.id); setError(""); try { const updated = user.status === "SUSPENDED" ? await adminApi.unsuspend(user.id) : await adminApi.suspend(user.id); setUsers((current) => current.map((item) => item.id === updated.id ? updated : item)); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "Account status could not be changed."); } finally { setActing(""); } }
  return <><header className="admin-page-header"><div><p className="eyebrow">Marketplace people</p><h1>Users</h1><p>Review verification and account access without exposing private documents.</p></div><span className="queue-count">{users.length} shown</span></header><div className="tabs"><button className={!filter ? "is-active" : ""} onClick={() => setFilter("")}>All</button><button className={filter === "PENDING_VERIFICATION" ? "is-active" : ""} onClick={() => setFilter("PENDING_VERIFICATION")}>Pending</button><button className={filter === "VERIFIED" ? "is-active" : ""} onClick={() => setFilter("VERIFIED")}>Verified</button><button className={filter === "SUSPENDED" ? "is-active" : ""} onClick={() => setFilter("SUSPENDED")}>Suspended</button></div>{error && <p className="form-error" role="alert">{error}</p>}<section className="admin-data-table card"><div className="admin-data-row admin-data-head"><span>User</span><span>Status</span><span>Trust</span><span>Action</span></div>{users.map((user) => <div className="admin-data-row" key={user.id}><span><strong>{user.fullName}</strong><small>{user.email} · {maskPhone(user.phoneNumber)}</small></span><span><b className={user.status === "VERIFIED" ? "status-chip status-chip--verified" : "status-chip status-chip--requested"}>{humanize(user.status)}</b><small>{user.kycStatus ? `KYC ${user.kycStatus.toLowerCase()}` : "No KYC"}</small></span><span>{Math.round(user.trustScore)} / 100</span><span><button className={user.status === "SUSPENDED" ? "button button--secondary button--small" : "button button--danger button--small"} disabled={acting === user.id || user.role === "ADMIN"} onClick={() => change(user)}>{user.status === "SUSPENDED" ? "Restore" : "Suspend"}</button></span></div>)}</section></>;
}
function maskPhone(value: string | null) { if (!value) return "No phone"; return value.length > 6 ? `${value.slice(0,4)}••••${value.slice(-3)}` : value; }
function humanize(value: string) { return value.toLowerCase().replaceAll("_", " ").replace(/^./, (letter) => letter.toUpperCase()); }
