"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { type FormEvent, useCallback, useEffect, useState } from "react";
import { ApiError } from "@/lib/api/client";
import { listingsApi, type Availability, type ListingDetail, type ListingStatus } from "@/lib/api/listings";

export function ListingManageView({ listingId }: { listingId: string }) {
  const router = useRouter();
  const [listing, setListing] = useState<ListingDetail | null>(null);
  const [availability, setAvailability] = useState<Availability | null>(null);
  const [error, setError] = useState("");
  const [saving, setSaving] = useState(false);
  const [photos, setPhotos] = useState<File[]>([]);
  const loadAvailability = useCallback(() => listingsApi.availability(listingId).then(setAvailability).catch(() => undefined), [listingId]);
  useEffect(() => { listingsApi.detail(listingId).then(setListing).catch(() => setError("This listing could not be loaded.")); void loadAvailability(); }, [listingId, loadAvailability]);

  async function save(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setSaving(true); setError(""); const form = new FormData(event.currentTarget);
    try { const updated = await listingsApi.update(listingId, { title: String(form.get("title")), description: String(form.get("description")), pricePerUnit: Number(form.get("price")), depositAmount: Number(form.get("deposit")), district: String(form.get("district")), locationText: String(form.get("locationText")), status: String(form.get("status")) as ListingStatus }); setListing(updated); if (photos.length) { await listingsApi.uploadImages(listingId, photos); setPhotos([]); setListing(await listingsApi.detail(listingId)); } } catch (caught) { setError(caught instanceof ApiError ? caught.message : "Changes could not be saved."); } finally { setSaving(false); }
  }
  async function block(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); const form = new FormData(event.currentTarget); try { setAvailability(await listingsApi.blockDates(listingId, { startDate: String(form.get("startDate")), endDate: String(form.get("endDate")), reason: String(form.get("reason")) || undefined })); event.currentTarget.reset(); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "Dates could not be blocked."); } }
  async function unblock(rangeId: string) { try { await listingsApi.unblockDates(listingId, rangeId); await loadAvailability(); } catch { setError("The blocked range could not be removed."); } }
  async function remove() { if (!window.confirm("Remove this listing from Rentle? Existing booking records will remain.")) return; try { await listingsApi.remove(listingId); router.push("/listings/manage"); } catch { setError("The listing could not be removed."); } }

  if (!listing) return <main className="page"><div className="container narrow-page"><p>{error || "Loading listing…"}</p></div></main>;
  return <main className="page"><div className="container narrow-page"><header className="page-header"><p className="eyebrow">Owner workspace</p><h1>Manage listing</h1><p><Link href={`/listing/${listing.id}`}>View public page</Link></p></header><form className="card card-pad form-grid" onSubmit={save}><div className="field"><label htmlFor="manage-title">Title</label><input id="manage-title" name="title" defaultValue={listing.title} minLength={5} maxLength={120} required /></div><div className="field"><label htmlFor="manage-description">Description</label><textarea id="manage-description" name="description" defaultValue={listing.description} minLength={20} maxLength={2000} required /></div><div className="form-grid form-grid--two"><div className="field"><label htmlFor="manage-price">Price</label><input id="manage-price" name="price" type="number" min="1" step="0.01" defaultValue={listing.pricePerUnit} required /></div><div className="field"><label htmlFor="manage-deposit">Deposit</label><input id="manage-deposit" name="deposit" type="number" min="0" step="0.01" defaultValue={listing.depositAmount} required /></div><div className="field"><label htmlFor="manage-district">District</label><input id="manage-district" name="district" defaultValue={listing.district} required /></div><div className="field"><label htmlFor="manage-location">Area</label><input id="manage-location" name="locationText" defaultValue={listing.locationText || ""} /></div></div><div className="field"><label htmlFor="manage-status">Publishing status</label><select id="manage-status" name="status" defaultValue={listing.status}><option value="ACTIVE">Active</option><option value="INACTIVE">Paused</option><option value="DRAFT">Draft</option></select></div><div className="field"><label htmlFor="manage-photos">Add photos</label><input id="manage-photos" type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={(event) => setPhotos(Array.from(event.target.files ?? []))} /><small>{photos.length ? `${photos.length} photo(s) selected` : `${listing.images.length} photo(s) currently attached`}</small></div>{error && <p className="form-error" role="alert">{error}</p>}<div className="button-row"><button className="button" disabled={saving}>{saving ? "Saving…" : "Save changes"}</button><button className="button button--secondary" type="button" onClick={remove}>Remove listing</button></div></form>
  <section className="card card-pad"><h2>Block unavailable dates</h2><form className="form-grid" onSubmit={block}><div className="form-grid form-grid--two"><div className="field"><label htmlFor="block-start">Start date</label><input id="block-start" name="startDate" type="date" required /></div><div className="field"><label htmlFor="block-end">End date</label><input id="block-end" name="endDate" type="date" required /></div></div><div className="field"><label htmlFor="block-reason">Private note (optional)</label><input id="block-reason" name="reason" maxLength={200} /></div><button className="button">Block dates</button></form><div className="profile-reviews">{availability?.blocked.map((range) => <div className="review" key={`${range.rangeId}-${range.startDate}`}><strong>{range.startDate} – {range.endDate}</strong><span>{range.source === "BOOKED" ? "Booked" : "Owner blocked"}</span>{range.rangeId && range.source === "OWNER_BLOCKED" && <button className="text-button" onClick={() => unblock(range.rangeId!)}>Remove block</button>}</div>)}</div></section></div></main>;
}
