"use client";

import { useState } from "react";
import { Check, ChevronRight, FileImage, ShieldCheck, X } from "lucide-react";

const initial = [
  { id: "VER-1048", name: "Anisha Karki", phone: "+977 98•• ••112", district: "Kathmandu", submitted: "11 Jul · 09:24", age: "2h" },
  { id: "VER-1047", name: "Rojen Tamang", phone: "+977 98•• ••447", district: "Lalitpur", submitted: "11 Jul · 08:51", age: "3h" },
  { id: "VER-1046", name: "Sujan Gurung", phone: "+977 98•• ••830", district: "Kaski", submitted: "10 Jul · 17:32", age: "18h" },
];

export function VerificationQueue() {
  const [items, setItems] = useState(initial); const [selected, setSelected] = useState(initial[0]); const [notice, setNotice] = useState(""); const [imageOpen, setImageOpen] = useState(false);
  function resolve(action: "approved" | "rejected") { setItems((current) => current.filter((item) => item.id !== selected.id)); setNotice(`${selected.name} was ${action}. The decision was recorded.`); const next = items.find((item) => item.id !== selected.id); if (next) setSelected(next); window.setTimeout(() => setNotice(""), 3500); }
  return <><header className="admin-page-header"><div><p className="eyebrow">Trust operations</p><h1>Verification queue</h1><p>Review citizenship cards against the account details. Oldest submissions appear first.</p></div><span className="queue-count">{items.length} pending</span></header><div className="admin-queue-layout"><section className="admin-table card"><div className="admin-table__head"><span>Applicant</span><span>District</span><span>Submitted</span><span /></div>{items.map((item) => <button key={item.id} className={selected.id === item.id ? "admin-row is-selected" : "admin-row"} onClick={() => setSelected(item)}><span><strong>{item.name}</strong><small>{item.phone} · {item.id}</small></span><span>{item.district}</span><span>{item.submitted}<small>{item.age} ago</small></span><ChevronRight size={17} /></button>)}</section><aside className="review-panel card"><header><div><p className="eyebrow">{selected.id}</p><h2>{selected.name}</h2><p>{selected.phone} · {selected.district}</p></div><span className="status-chip status-chip--requested">Pending</span></header><div className="document-viewer"><FileImage size={34} /><strong>Citizenship card — front</strong><small>Click to inspect at full resolution</small><button className="button button--secondary button--small" onClick={() => setImageOpen(true)}>Open image</button></div><dl><div><dt>Name on account</dt><dd>{selected.name}</dd></div><div><dt>Issued district</dt><dd>{selected.district}</dd></div><div><dt>Document number</dt><dd>27-01-78-01•••</dd></div><div><dt>Phone verified</dt><dd><ShieldCheck size={15} /> Yes</dd></div></dl><div className="review-panel__actions"><button className="button button--danger" onClick={() => resolve("rejected")}><X size={17} /> Reject</button><button className="button" onClick={() => resolve("approved")}><Check size={17} /> Approve</button></div></aside></div>{imageOpen && <div className="document-modal" role="dialog" aria-modal="true" aria-label="Citizenship card image"><header><div><strong>{selected.name}</strong><small>{selected.id} · front</small></div><button className="icon-button" aria-label="Close image" onClick={() => setImageOpen(false)}><X /></button></header><div><FileImage size={52} /><strong>Protected citizenship image preview</strong><span>Full-resolution document viewer placeholder</span></div></div>}{notice && <div className="toast"><Check size={18} />{notice}</div>}</>;
}
