"use client";

import { useEffect, useState } from "react";
import { Check, ChevronRight, FileCheck2, ShieldCheck } from "lucide-react";
import { adminApi } from "@/lib/api/admin";
import { ApiError } from "@/lib/api/client";
import type { UserProfile } from "@/lib/api/users";

export function VerificationQueue() {
  const [items, setItems] = useState<UserProfile[]>([]); const [selectedId, setSelectedId] = useState(""); const [notice, setNotice] = useState(""); const [error, setError] = useState(""); const [acting, setActing] = useState(false);
  useEffect(() => { adminApi.users("PENDING_VERIFICATION", 0, 100).then((page) => { const pending = page.content.filter((user) => user.citizenshipUploaded && !user.citizenshipVerified); setItems(pending); setSelectedId(pending[0]?.id || ""); }).catch((caught) => setError(caught instanceof ApiError ? caught.message : "Verification requests could not be loaded.")); }, []);
  const selected = items.find((item) => item.id === selectedId) || items[0];
  async function approve() { if (!selected) return; setActing(true); setError(""); try { await adminApi.verify(selected.id); const remaining = items.filter((item) => item.id !== selected.id); setItems(remaining); setSelectedId(remaining[0]?.id || ""); setNotice(`${selected.fullName} was verified.`); window.setTimeout(() => setNotice(""), 3500); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "Verification could not be approved."); } finally { setActing(false); } }

  return <><header className="admin-page-header"><div><p className="eyebrow">Trust operations</p><h1>Verification queue</h1><p>Approve users whose phone and uploaded citizenship status have been checked through the protected operations process.</p></div><span className="queue-count">{items.length} pending</span></header>{error && <p className="form-error" role="alert">{error}</p>}{selected ? <div className="admin-queue-layout"><section className="admin-table card"><div className="admin-table__head"><span>Applicant</span><span>Phone</span><span>Submitted</span><span /></div>{items.map((item) => <button key={item.id} className={selected.id === item.id ? "admin-row is-selected" : "admin-row"} onClick={() => setSelectedId(item.id)}><span><strong>{item.fullName}</strong><small>{item.email}</small></span><span>{maskPhone(item.phoneNumber)}</span><span>{formatDate(item.createdAt)}</span><ChevronRight size={17} /></button>)}</section><aside className="review-panel card"><header><div><p className="eyebrow">Account #{selected.id.slice(0,8)}</p><h2>{selected.fullName}</h2><p>{selected.email}</p></div><span className="status-chip status-chip--requested">Pending</span></header><div className="document-viewer"><FileCheck2 size={34} /><strong>Citizenship document uploaded</strong><small>The current admin API exposes upload status, not document contents. Review documents only in an approved protected viewer.</small></div><dl><div><dt>Phone verified</dt><dd><ShieldCheck size={15} /> {selected.phoneVerified ? "Yes" : "No"}</dd></div><div><dt>Document uploaded</dt><dd>{selected.citizenshipUploaded ? "Yes" : "No"}</dd></div><div><dt>Trust score</dt><dd>{Math.round(selected.trustScore)} / 100</dd></div><div><dt>Account created</dt><dd>{formatDate(selected.createdAt)}</dd></div></dl><div className="review-panel__actions"><button className="button" disabled={acting || !selected.phoneVerified || !selected.citizenshipUploaded} onClick={approve}><Check size={17} /> {acting ? "Approving…" : "Approve verification"}</button></div></aside></div> : !error && <section className="empty-state card"><p className="eyebrow">Queue clear</p><h2>No uploaded citizenship cards are waiting.</h2><p>New eligible submissions will appear here.</p></section>}{notice && <div className="toast"><Check size={18} />{notice}</div>}</>;
}
function maskPhone(value: string) { return value.length > 6 ? `${value.slice(0,4)}••••${value.slice(-3)}` : value; }
function formatDate(value: string) { return new Intl.DateTimeFormat("en", { day: "numeric", month: "short", year: "numeric" }).format(new Date(value)); }
